### ISSUE TITLE
bug: flickering and jitter due to Refined Github

### ISSUE THREAD

**Issue by lrstanley** [Gerrit0/old-github-feed#1]
Testing this out with ViolentMonkey on Firefox, and I'm seeing the following:

![](https://cdn.liam.sh/share/2022/10/firefox_FhqQt2YggB.gif)

I also use the Refined Github extension, which adds various features, and it looks like there might be some conflicts there, that may be worth calling out in the readme and/or script, as I imagine a lot of folks also use Refined Github.

Disabling this specific feature in Refined Github resolves the flickering issues:
![](https://cdn.liam.sh/share/2022/10/firefox_Zf4e2DtfnF.png)

Just in case others run into this issue as well!

**Comment by Gerrit0** [comment]
This is caused by the MutationObserver, which is added so that the feed doesn't get refreshed by GitHub to point to the new feed (it tries every 60 seconds)... could potentially fix it by adding logic in the callback passed to the observer to only do things if there are added nodes, since I suspect Refined GitHub only removes nodes.

**Comment by Gerrit0** [comment]
Potential fix - could you try changing the observer initialization to this?

```js
    const observer = new MutationObserver((mutations) => {
        if (mutations.some(m => m.addedNodes.length)) {
            fixDashboard();
        }
    });
```

**Comment by lrstanley** [comment]
Tested -- seems to make the jitter worse (the entire feed viewport, not just the bottom portion).

**Comment by lrstanley** [comment]
For reference, [this is the source](https://github.com/refined-github/refined-github/blob/main/source/features/hide-own-stars.tsx) for the "hide own stars" feature in Refined Github.

**Comment by Gerrit0** [comment]
Unfortunate, going to be difficult to debug this one, I can't reproduce, possibly don't have enough other events in my newsfeed... Might be able to do something like this?

```js
    const observer = new MutationObserver(() => {
        if (displayedDashboard.querySelector(".js-feed-item-component")) {
            fixDashboard();
        }
    });
```

**Comment by lrstanley** [comment]
That looks to work perfectly, no more jitter.
