### ISSUE TITLE
Header boxes disappear on iOS

### ISSUE THREAD

**Issue by jevinskie** [Gerrit0/old-github-feed#11]
Seems something changed and now I’m missing the usual header boxes on iOS (they show up fine as sidebars on Mac Safari). I’m no good at responsive design so I can take a look with web inspector but probably won’t be able to divine much by myself. Not sure when it changed because I realized today my install of the user script wasn’t updating and went from some unknown old version to 0.11 just now.

With userscript:
![IMG_3472](https://github.com/Gerrit0/old-github-feed/assets/187848/bca99b21-5748-4722-9a9f-f7a0a4692722)

Without:

![IMG_3473](https://github.com/Gerrit0/old-github-feed/assets/187848/ba06e879-22bb-492a-9527-b984755150f7)
![IMG_3474](https://github.com/Gerrit0/old-github-feed/assets/187848/973b7c41-297a-4977-8be4-d9489a87ddcf)

**Comment by jevinskie** [comment]
Oh… they don’t disappear, they show up at the bottom!

![IMG_3496](https://github.com/Gerrit0/old-github-feed/assets/187848/602b66b8-a04c-4786-a75a-6b12b2352ac2)

**Comment by Gerrit0** [comment]
Still non-ideal! I'll take a look when off tomorrow

**Comment by jevinskie** [comment]
Beautiful, works a charm! Thank you so much! 🥇
