### ISSUE TITLE
Are there plans to remove the Copilot?

### ISSUE THREAD

**Issue by cotes2020** [Gerrit0/old-github-feed#18]
Hi there,

Recently, the Copilot has been added to the top of the feed, and there have been related [complaints](https://github.com/orgs/community/discussions/146375) in the GitHub community. So I want to know if you have plans to remove Copilot in the script?

<img width="350" alt="feed" src="https://github.com/user-attachments/assets/11700f9a-46e9-486d-8355-169814affdc8">

Since I have implemented this feature in a customized version, I can submit a PR to help if you are interested.

**Comment by Gerrit0** [comment]
Go for it!
