### ISSUE TITLE
v0.7 causing home page to freeze

### ISSUE THREAD

**Issue by b0o** [Gerrit0/old-github-feed#6]
Tampermonkey auto-updated to this script 0.7, and this caused my GitHub homepage to start freezing. Downgrading to 0.6 fixed the problem. There's no relevant messages in the JS console. Seems like some sort of infinite loop.

![2023-09-13_14-39-35_firefoxdeveloperedition](https://github.com/Gerrit0/old-github-feed/assets/21299126/5d6ff317-c3b7-4011-8e55-9f478a9c809a)

**Comment by Gerrit0** [comment]
Do you have any other browser extensions/userscripts enabled that could be interfering? I'm not able to replicate this.

**Comment by dxball** [comment]
I got freezing after install this script too

Browser: Brave 1.58.124
OS: Windows 10

I try to disable all extension I've install, but still same result
